name = "Neo Yokohama Race Cource"
author = "Mecha"
version = "2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "211dad5fca7dc17589dd8c29d32628b11ddcfea42fa26017aa4f9da83773b551"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
