name = "Neo Yokohama Race Cource"
author = "Mecha"
version = "2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "982285d96001f7cf18335436bd04d6d83fb241eeff6379ba68982870170e44df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
