name = "Neo Yokohama Race Cource"
author = "Mecha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1661c5d18cb658737aaaf8c9a53c0d42ac5338c0aa7e14fde5f59e1d1aaea2c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
